[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "ruff"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language.formatter]
command = "ruff"
args = ["format", "-"]
