### --- LANGUAGE SERVER SETUP - HELIX --- ###

# -- PYTHON -- #
[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright"]
formatter = { command = "ruff", args = [ "format", "-"] }

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

# -- RUST -- #
[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true


# -- LUA -- #
[[language]]
name = "lua"
language-servers = ["lua-language-server"]
formatter = { command = "stylua", args = ["-"]}
auto-format = true

