-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- HYPRLAND AUTOSTART CONFIGURATION --- #

-- exec-once = swww-daemon &

-- exec-once = swww img ~/.local/share/wallpapers/wallpaper.png -t none

-- exec-once = nm-applet --indicator

-- exec-once = blueman-applet

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("dunst")
    hl.exec_cmd("waytrogen --restore")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/pam_kwallet_init")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("pactl set-sink-volume alsa_output.pci-0000_06_00.6.analog-stereo 71%")
    hl.exec_cmd("snappy-switcher --daemon")
end)
