-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- HYPRLAND COLORS CONFIGURATION --- #

-- Catppuccin Mocha Colors

local rosewater = "rgb(f5e0dc)"

local flamingo = "rgb(f2cdcd)"

local pink = "rgb(f5c2e7)"

local mauve = "rgb(cba6f7)"

local red = "rgb(f38ba8)"

local maroon = "rgb(eba0ac)"

local peach = "rgb(fab387)"

local yellow = "rgb(f9e2af)"

local green = "rgb(a6e3a1)"

local teal = "rgb(94e2d5)"

local sky = "rgb(89dceb)"

local sapphire = "rgb(74c7ec)"

local blue = "rgb(89b4fa)"

local lavender = "rgb(b4befe)"

local text = "rgb(cdd6f4)"

local subtext1 = "rgb(bac2de)"

local subtext0 = "rgb(a6adc8)"

local overlay2 = "rgb(9399b2)"

local overlay1 = "rgb(7f849c)"

local overlay0 = "rgb(6c7086)"

local surface2 = "rgb(585b70)"

local surface1 = "rgb(45475a)"

local surface0 = "rgb(313244)"

local base = "rgb(1e1e2e)"

local mantle = "rgb(181825)"

local crust = "rgb(11111b)"

return {
    rosewater = rosewater,
    flamingo = flamingo,
    pink = pink,
    mauve = mauve,
    red = red,
    maroon = maroon,
    peach = peach,
    yellow = yellow,
    green = green,
    teal = teal,
    sky = sky,
    sapphire = sapphire,
    blue = blue,
    lavender = lavender,
    text = text,
    subtext1 = subtext1,
    subtext0 = subtext0,
    overlay2 = overlay2,
    overlay1 = overlay1,
    overlay0 = overlay0,
    surface2 = surface2,
    surface1 = surface1,
    surface0 = surface0,
    base = base,
    mantle = mantle,
    crust = crust,
}
