-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- HYPRLAND ENVIRONMENT VARIABLES --- #

hl.env("XCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("GDK_BACKEND", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")
