-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- HYPRLAND MONITOR CONFIGURATIONS --- #

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "highrr",
    position = "auto",
    scale    = 1,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "highrr",
    position = "auto",
    scale    = 1,
})

hl.workspace_rule({
    workspace = 1,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "eDP-1",
})
