-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- HYPRLAND SETTINGS --- #

-- source = ~/.config/hypr/configs/colors.conf -> requires manual conversion
local colors = require("configs.colors")
-- TODO: convert ~/.config/hypr/configs/colors.conf to .lua and use require()

-- General settings

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",
        resize_on_border = true,
        col = {
            active_border = { colors = { colors.teal, colors.blue }, angle = 45 },
            inactive_border = colors.surface0,
        },
    },
})

-- Misc settings

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        vrr = 1,
        enable_swallow = true,
        swallow_regex = "^(kitty)$",
    },
})
