# --- HYPRLAND VISUAL CONFIGURATIONS --- #

source = ~/.config/hypr/configs/colors.conf

# Decoration
decoration {
    rounding = 10
    
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

   # drop_shadow = true
   # shadow_range = 20
   # shadow_render_power = 3
   # col.shadow = rgba(1a1a1aee)
    
    blur {
        enabled = true
        size = 6
        passes = 3
        ignore_opacity = true

        new_optimizations = true
        xray = true

        noise = 0.12
        contrast = 1.5
    }
}

# Animations
animations {
    enabled = true
    
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.0
    bezier = winOut, 0.3, 0, 0.8, 0.15
    bezier = liner, 1, 1, 1, 1
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 4, winOut, popin 80%
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 3, linear
    animation = borderangle, 1, 100, linear, loop
    animation = fade, 1, 3, default
    animation = workspaces, 1, 5, wind
    animation = specialWorkspace, 1, 5, wind, slidevert
}

# Layouts
dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
}

# Windowrules
windowrule {
    name = floating-nmtui
    match:class = kitty
    match:title = nmtui

    # animation = popin
    size = 1000 800
    float = true
    center = true
}
