## -------- TMUX CONFIG ----------- ##

## -------- KEYBINDING RELATED SETTINGS ----------- ##

set-option -sa terminal-overrides ",xterm*:Tc"

# -- SET PREFIX KEY OF YOUR CHOICE -- ##
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
set -g mouse on

unbind r
bind r source-file ~/.tmux.conf

## -- SET VIM LIKE MOTIONS FOR PANES -- ##
bind-key h select-pane -L
bind-key k select-pane -D
bind-key j select-pane -U
bind-key l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


## ----------- Plugin specific Settings -------------- ##

set -g @rose_pine_variant 'moon'
set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_hostname_short 'on' # Makes the hostname shorter by using tmux's '#h' format
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar

set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder
set -g @rose_pine_username_icon '' # Changes the default icon to the right of the hostname
set -g @rose_pine_hostname_icon '󰒋' # Changes the default icon to the right of the hostname

## -- List of plugins -- ##

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'rose-pine/tmux'

run '~/.tmux/plugins/tpm/tpm'
